version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wordpress:/var/www/html
       - ./my-theme:/var/www/html/wp-content/themes/my-theme
       - ./my-plugin:/var/www/html/wp-content/plugins/my-plugin
     ports:
       - "8000:80"
     restart: always
     environment:
       TZ: 'Asia/Tokyo'
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       
   wpcli:
     container_name: wpcli
     image: wordpress:cli-php7.4
     working_dir: /var/www/html
     depends_on:
       - wordpress
       - db
     volumes:
       - ./wordpress:/var/www/html
       - ./my-theme:/var/www/html/wp-content/themes/my-theme
       - ./my-plugin:/var/www/html/wp-content/plugins/my-plugin
     command: "--info"
     user: xfs
volumes:
    db_data:
